In [1]:
#Introduction to Machine Learning:
# Machine Learning is a branch of Artificial Intelligence (AI) that enables computers or systems to automatically learn from experience(data)
# and improve their performance on a task without being explicitly programmed.

#Steps to Train a Machine Learning Model:
#1. Import Libraries
#2. Load and Understand the Data
#3. Data Cleaning and Preprocessing
    #Handle missing values
    # Encode categorical variables
    # Normalize or scale values
    # Split into features (X) and target (y)
#4. Split the Data  :   Split the dataset into training and testing sets (e.g., 80%-20%)
#5. Model selection: Pick a model suitable for your task (e.g., classification or regression).
#6. Model Training: Fit the model on the training data.(model.fit(X_train, y_train))
#7. Model Evaluation: to check the model accuracy
#8. Improve the Model (Optional):
          # Trying different models
          # Tuning
          # Feature engineering
          # Using more data



In [3]:
#Feature Engineering:
# Feature Engineering is the process of selecting, transforming, or creating input features from raw data 
# to improve the performance of a machine learning model.
#It includes parts of data preprocessing and data cleaning

In [12]:
# Standardization is the process of transforming numerical features in a dataset so that they have:
# a mean (μ) of 0, and
# a standard deviation (σ) of 1

# Standardization Formula:
# z=(𝑥-μ)/𝜎


# Where:
# 𝑥: original feature value
# 𝜇: mean of the feature
# 𝜎: standard deviation of the feature
# 𝑧: standardized value

In [ ]:
#Normalization: Normalization is a data preprocessing technique used to rescale numerical features so that they fall within a 
#specific range, typically [0, 1].

#Normalization is the process of transforming features so that they fall within a fixed range (usually 0 to 1), using the formula:

In [ ]:
# | Technique           | Range Target     | Use Case                          |
# | ------------------- | ---------------- | --------------------------------- |
# | **Standardization** | Mean = 0, SD = 1 | When data is normally distributed |
# | **Normalization**   | Range \[0, 1]    | When you need bounded values      |


In [ ]:
#1.Data Dividation:
#after data collection and data preprocesssing, data dividation is done.
#THe dataaframe is dividedinto two parts: 1. input(x) 2.target(y) where(df=input+target)
#from x, x_train,x_test is created   ..... x is independent data
#from y,y_train,y_test is created    ..... y is dependent data
#we divide data in two parts: training and testimg data.. where majority data is for training and minority data is for testing

In [2]:
import numpy as np
import pandas as pd

In [6]:
df=pd.read_csv("placement.csv")
df.head(2)

cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0

In [10]:
df.shape

(100, 3)

In [12]:
#on the basis of cgpa and resume_score, a student is placed or not is defined so "placed" target column here.
#so, cgpa and resume_score is independent data and placed is dependent data


In [22]:
#drop the dependent data(x stores the independent data)
x=df.drop(columns=["placed"])
print(x)
print(x.shape)

    cgpa  resume_score
0   8.14          6.52
1   6.17          5.17
2   8.27          8.86
3   6.88          7.27
4   7.52          7.30
..   ...           ...
95  6.33          6.38
96  8.23          7.76
97  6.65          7.78
98  8.14          5.63
99  6.09          6.61

[100 rows x 2 columns]
(100, 2)


In [26]:
#y stores the target column(dependent data)
y=df["placed"]
print(y)
print(y.shape)

0     1
1     0
2     1
3     1
4     1
     ..
95    0
96    1
97    0
98    1
99    0
Name: placed, Length: 100, dtype: int64
(100,)


In [46]:
#JUST READ
a=np.random.randint(1,10,3)  #it means give 3 random numbers b/w 1 and 10...it could be any number.
a
#this will generate different three number every time it runs, thats why seed function came into existence

array([7, 3, 6])

In [48]:
np.random.seed(6)  # pass any number inside seed function, its irrelevant
b=np.random.randint(1,10,3)
b

#it has fixed the generated number, even we run it mora than one time the generated number does not chnage, this is what seed function does.

array([4, 5, 1])

In [50]:
#seed function
# | Term     | Meaning                               |
# | -------- | ------------------------------------- |
# | `seed()` | Fixes the randomness                  |
# | Use case | Ensures same results on multiple runs |
# | Value    | Any integer (e.g., `42`, `0`, `1`)    |


In [106]:
from sklearn.model_selection import train_test_split

In [108]:
#data is divided into 4 parts
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)   #random_state is just like seed() function in python, it is creating the data at once and locking the value.

In [110]:
print(f"Total Data Shape:{df.shape},x data shape:{x.shape},y data shape:{y.shape}")    #x+y=df(1+2=3)
print("x_train shape:",x_train.shape)
print("x_test shape:",x_test.shape)
print("y_train shape:",y_train.shape)
print("y_test shape:",y_test.shape)

Total Data Shape:(100, 3),x data shape:(100, 2),y data shape:(100,)
x_train shape: (80, 2)
x_test shape: (20, 2)
y_train shape: (80,)
y_test shape: (20,)


In [ ]:
##this is how exactly data dividation occured:
#df(100,3)=x(80,2) + y(20,2)   (means x+y=df)
#x(100,2)=x_train(80,2) + x_test(20,2)   (means x_train+x_test=x)
#y(100,1)=y_train(80,)1 + y_test(20,1)   (means y_train+y_test=y)

In [112]:
df1=pd.read_csv("covid_toy.csv")
df1.head(2)

age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [114]:
df1.isnull().sum()

#we can see that fever column has 10 null values

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [116]:
#average of fever column
df1["fever"].mean()

100.84444444444445

In [118]:
df1["fever"]=df1["fever"].fillna(df1["fever"].mean())
print(df1.isnull().sum())   #now our data has no missing values and fever column missing value is filled with mean value of it

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64


In [120]:
df1["gender"].value_counts()  #in a categorical column how many sub-categories are there is checked by value_counts

gender
Female    59
Male      41
Name: count, dtype: int64

In [122]:
df1["gender"]=df1["gender"].map({"Female":0,"Male":1})   #map is used when we want to do a change in every element of data
df1["cough"]=df1["cough"].map({"Mild":0,"Strong":1})
df1["city"]=df1["city"].map({"Kolkata":0,"Bangalore":1,"Delhi":2,"Mumbai":3})
df1["has_covid"]=df1["has_covid"].map({"No":0,"Yes":1})

In [124]:
df1    #data cleaning and pre_processing has been done using pandas only

age  gender  fever  cough  city  has_covid
0    60       1  103.0      0     0          0
1    27       1  100.0      0     2          1
2    42       1  101.0      0     2          0
3    31       0   98.0      0     0          0
4    65       0  101.0      0     3          0
..  ...     ...    ...    ...   ...        ...
95   12       0  104.0      0     1          0
96   51       0  101.0      1     0          1
97   20       0  101.0      0     1          0
98    5       0   98.0      1     3          0
99   10       0   98.0      1     0          1

[100 rows x 6 columns]

In [150]:
#train test split:
from sklearn.model_selection import train_test_split

# Define features and target
X=df1.drop("has_covid",axis=1)
y=df1["has_covid"]
print(X)
print(y)


#split the data:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)


    age  gender  fever  cough  city
0    60       1  103.0      0     0
1    27       1  100.0      0     2
2    42       1  101.0      0     2
3    31       0   98.0      0     0
4    65       0  101.0      0     3
..  ...     ...    ...    ...   ...
95   12       0  104.0      0     1
96   51       0  101.0      1     0
97   20       0  101.0      0     1
98    5       0   98.0      1     3
99   10       0   98.0      1     0

[100 rows x 5 columns]
0     0
1     1
2     0
3     0
4     0
     ..
95    0
96    1
97    0
98    0
99    1
Name: has_covid, Length: 100, dtype: int64


In [156]:
# Print data shapes:
print("full data shape:",df1.shape)
print(f"X shape:{X.shape} and y shape:{y.shape}")
print("X_train shape:",X_train.shape)
print("X_test shape:",X_test.shape)
print("y_train shape:",y_train.shape)
print("y_test shape:",y_test.shape)

full data shape: (100, 6)
X shape:(100, 5) and y shape:(100,)
X_train shape: (80, 5)
X_test shape: (20, 5)
y_train shape: (80,)
y_test shape: (20,)


In [158]:
# Why is it called train_test_split?
# Because it splits your full dataset into:
# Training data → This part will be used to train the model
# Testing data → This part will be used to test (evaluate) the model after it's trained


In [174]:
#Normal Distribution:
#A normal distribution, also known as a Gaussian distribution, is a probability distribution that is symmetrical and bell-shaped.

# Symmetry:
# The distribution is symmetrical around its mean, meaning that the left and right sides are mirror images of each other. 
# Bell-shaped:
# The curve resembles a bell, with the highest point at the mean.


# Mean, Median, and Mode are Equal:
# In a normal distribution, the mean, median, and mode all have the same value. 

In [176]:
np.round(X_train.describe(),2)  #we can see that average is different for each column and also next value gap i.e. is not fixed

#it means that our data is not normally distributed

age  gender   fever  cough   city
count  80.00   80.00   80.00  80.00  80.00
mean   42.91    0.41  100.98   0.40   1.26
std    24.47    0.50    1.93   0.49   1.06
min     5.00    0.00   98.00   0.00   0.00
25%    20.00    0.00  100.00   0.00   0.00
50%    42.00    0.00  101.00   0.00   1.00
75%    65.00    1.00  102.00   1.00   2.00
max    84.00    1.00  104.00   1.00   3.00

In [180]:
#to perform normal distribution in ml:
from sklearn.preprocessing import StandardScaler

# from sklearn.preprocessing import StandardScaler — What does it mean?
# This line imports the StandardScaler class from sklearn.preprocessing, which is part of the scikit-learn machine learning library in Python.
# What is StandardScaler?
# StandardScaler is used to standardize (scale) features so that:
# The mean of each feature becomes 0
# The standard deviation becomes 1
# 📌 This is called Z-score normalization.

In [182]:
scaler=StandardScaler()    # an object of standard scaler is created

In [186]:
X_train_sc=scaler.fit_transform(X_train)

# | Function          | Meaning                                                              |
# | ----------------- | -------------------------------------------------------------------- |
# | `fit()`           | **Learns** the parameters (mean & standard deviation) from the data  |
# | `transform()`     | **Applies** those learned parameters to standardize (scale) the data |
# | `fit_transform()` | Combines both steps: learn + apply in one line                       |

# scaler learns the parameters from X_train.
# A scaler is a tool (a class or object) in machine learning that adjusts the values of your data — so they are easier for a model to understand.


In [190]:
X_train_sc   #converted into array form

array([[ 1.56614097, -0.83793058,  0.00912571, -0.81649658,  1.64281485],
       [-1.55894504, -0.83793058, -0.51234344, -0.81649658, -1.1937    ],
       [-0.98327131, -0.83793058, -0.51234344, -0.81649658, -1.1937    ],
       [-0.65431488,  1.19341628, -0.51234344, -0.81649658,  0.6973099 ],
       [ 1.23718454, -0.83793058,  1.05206401, -0.81649658,  0.6973099 ],
       [ 1.11382589,  1.19341628,  1.05206401,  1.22474487, -1.1937    ],
       [ 0.25031528, -0.83793058,  0.53059486, -0.81649658,  0.6973099 ],
       [ 0.33255438, -0.83793058,  0.00912571,  1.22474487, -1.1937    ],
       [ 0.86710857, -0.83793058,  0.00912571, -0.81649658,  0.6973099 ],
       [ 1.64838007, -0.83793058,  0.00912571, -0.81649658, -1.1937    ],
       [ 0.90822812, -0.83793058, -1.55528174, -0.81649658,  1.64281485],
       [-1.02439086, -0.83793058,  1.57353316, -0.81649658, -0.24819505],
       [-1.10662996, -0.83793058,  1.05206401, -0.81649658, -0.24819505],
       [-1.10662996,  1.19341628,  1.5

In [196]:
X_train_new=pd.DataFrame(X_train_sc,columns=X.columns)

In [198]:
np.round(X_train_new.describe(),2)

#we can see mean is same for all data and std(gap) is same.. it means that our data is now normally distributed where central tendency is 0 and next value gap is 1.01.

age  gender  fever  cough   city
count  80.00   80.00  80.00  80.00  80.00
mean   -0.00    0.00  -0.00  -0.00   0.00
std     1.01    1.01   1.01   1.01   1.01
min    -1.56   -0.84  -1.56  -0.82  -1.19
25%    -0.94   -0.84  -0.51  -0.82  -1.19
50%    -0.04   -0.84   0.01  -0.82  -0.25
75%     0.91    1.19   0.53   1.22   0.70
max     1.69    1.19   1.57   1.22   1.64